version: '3.8'

services:
  bot:
    build: .
    container_name: telegram-countdown-bot
    environment:
      - TOKEN=${TOKEN}  # Telegram bot token from environment variable
      - UPDATE_INTERVAL=${UPDATE_INTERVAL}  # Update interval in seconds
    volumes:
      - ./data:/app/data  # Persist countdown data
    restart: unless-stopped
